// PERC Key Management — Key generation, EKT wrapping, and key hierarchy.
//
// Key hierarchy (per RFC 8871 / RFC 8870):
//
//   KEK (Key Encrypting Key) — shared by KD and all endpoints, never given to SFU
//    └─ wraps per-sender E2E SRTP master keys in EKT Full Tags
//
//   E2E master key + salt — per sender, used for inner SRTP encryption
//    └─ derived into RTP/RTCP cipher keys via SRTP KDF
//
//   HBH master key + salt — per hop (endpoint↔SFU), from DTLS-SRTP
//    └─ derived into RTP/RTCP cipher keys via SRTP KDF
//
// The KD generates KEK and E2E keys. HBH keys come from DTLS-SRTP (not managed here).

'use strict';

const crypto = require('node:crypto');

// SRTP profile: DOUBLE_AEAD_AES_128_GCM_AEAD_AES_128_GCM
// Total keying material: 256-bit key (128 inner + 128 outer), 192-bit salt (96 inner + 96 outer)
const SRTP_KEY_LEN = 16;       // 128 bits per layer
const SRTP_SALT_LEN = 12;      // 96 bits per layer
const KEK_LEN = 16;            // AES-128 for EKT key wrapping
const EKT_SPI_LEN = 2;         // Security Parameter Index (16-bit)

class KeyManager {
    constructor() {
        // KEK: Key Encrypting Key for EKT (shared with endpoints, NOT with SFU)
        this.kek = null;
        this.kekSpi = 0;   // incremented on KEK rotation

        // Per-conference shared E2E salt (distributed by KD to all endpoints)
        this.e2eSalt = null;

        // Shared conference-wide E2E group key. Every endpoint encrypts and
        // decrypts with this single key so any participant can decrypt any
        // other participant's media (SFrame-style group keying). This is the
        // simplest interoperable model for a mesh of senders behind an SFU
        // that may rewrite SSRCs.
        this.e2eGroupKey = null;

        // Per-endpoint E2E master keys (generated by endpoints, wrapped with KEK in EKT)
        // Map<endpointId, { masterKey, ssrc, roc }>
        this.endpointKeys = new Map();
    }

    // Generate a new KEK for the conference.
    generateKek() {
        this.kek = crypto.randomBytes(KEK_LEN);
        this.kekSpi++;
        this.e2eSalt = crypto.randomBytes(SRTP_SALT_LEN);
        if (!this.e2eGroupKey) {
            this.e2eGroupKey = crypto.randomBytes(SRTP_KEY_LEN);
        }
        return {
            kek: this.kek,
            kekSpi: this.kekSpi,
            e2eSalt: this.e2eSalt,
        };
    }

    // Generate an E2E SRTP master key for an endpoint.
    // In full PERC, endpoints generate their own keys and share via EKT.
    // Here the KD generates them for simplicity.
    generateEndpointE2eKey(endpointId, ssrc) {
        const masterKey = crypto.randomBytes(SRTP_KEY_LEN);
        const entry = { masterKey, ssrc, roc: 0 };
        this.endpointKeys.set(endpointId, entry);
        return entry;
    }

    // Build an EKT Full Tag for an endpoint's E2E key.
    // Per RFC 8870 §4.1:
    //   FullEKTTag = EKTCiphertext || SPI || Length
    //   EKTCiphertext = AES-KeyWrap(KEK, SRTPMasterKey || SSRC || ROC)
    buildEktFullTag(endpointId) {
        const entry = this.endpointKeys.get(endpointId);
        if (!entry || !this.kek) return null;

        // Plaintext to wrap: master key (16B) + SSRC (4B) + ROC (4B) = 24 bytes
        const plaintext = Buffer.alloc(SRTP_KEY_LEN + 4 + 4);
        entry.masterKey.copy(plaintext, 0);
        plaintext.writeUInt32BE(entry.ssrc, SRTP_KEY_LEN);
        plaintext.writeUInt32BE(entry.roc, SRTP_KEY_LEN + 4);

        // AES Key Wrap (RFC 3394)
        const ciphertext = aesKeyWrap(this.kek, plaintext);

        // Build tag: ciphertext || SPI (2B) || length (2B)
        const spi = Buffer.alloc(EKT_SPI_LEN);
        spi.writeUInt16BE(this.kekSpi);

        const length = Buffer.alloc(2);
        length.writeUInt16BE(ciphertext.length + EKT_SPI_LEN + 2);

        return Buffer.concat([ciphertext, spi, length]);
    }

    // Parse an EKT Full Tag received from an endpoint.
    parseEktFullTag(tag) {
        if (!this.kek || tag.length < EKT_SPI_LEN + 2) return null;

        const length = tag.readUInt16BE(tag.length - 2);
        const spi = tag.readUInt16BE(tag.length - 4);
        const ciphertext = tag.subarray(0, tag.length - 4);

        const plaintext = aesKeyUnwrap(this.kek, ciphertext);
        if (!plaintext) return null;

        return {
            masterKey: plaintext.subarray(0, SRTP_KEY_LEN),
            ssrc: plaintext.readUInt32BE(SRTP_KEY_LEN),
            roc: plaintext.readUInt32BE(SRTP_KEY_LEN + 4),
            spi,
        };
    }

    // Get the key bundle to send to an endpoint when it joins.
    getEndpointKeyBundle(endpointId) {
        const e2eKey = this.endpointKeys.get(endpointId);
        if (!e2eKey || !this.kek) return null;

        return {
            kek: this.kek.toString('base64'),
            kekSpi: this.kekSpi,
            e2eSalt: this.e2eSalt.toString('base64'),
            // Hand out the shared conference group key so every endpoint can
            // decrypt every other endpoint's media.
            e2eMasterKey: this.e2eGroupKey.toString('base64'),
            ssrc: e2eKey.ssrc,
        };
    }

    // Get all E2E keys (for distributing to other endpoints in the conference).
    getAllE2eKeys() {
        const keys = {};
        for (const [id, entry] of this.endpointKeys) {
            keys[id] = {
                masterKey: entry.masterKey.toString('base64'),
                ssrc: entry.ssrc,
            };
        }
        return keys;
    }

    // Rotate KEK (e.g., when a participant leaves).
    rotateKek() {
        return this.generateKek();
    }

    removeEndpoint(endpointId) {
        this.endpointKeys.delete(endpointId);
    }
}

// AES Key Wrap (RFC 3394) — wraps plaintext with AES-128 key.
// Plaintext must be a multiple of 8 bytes.
function aesKeyWrap(kek, plaintext) {
    if (plaintext.length % 8 !== 0) {
        throw new Error('AES Key Wrap: plaintext must be multiple of 8 bytes');
    }

    const n = plaintext.length / 8;
    let a = Buffer.from('A6A6A6A6A6A6A6A6', 'hex'); // default IV per RFC 3394
    const r = [];
    for (let i = 0; i < n; i++) {
        r.push(Buffer.from(plaintext.subarray(i * 8, (i + 1) * 8)));
    }

    for (let j = 0; j < 6; j++) {
        for (let i = 0; i < n; i++) {
            const input = Buffer.concat([a, r[i]]);
            const cipher = crypto.createCipheriv('aes-128-ecb', kek, null);
            cipher.setAutoPadding(false);
            const b = Buffer.concat([cipher.update(input), cipher.final()]);

            // XOR MSB(B) with t where t = n*j + i + 1
            const t = BigInt(n * j + i + 1);
            const aBytes = Buffer.from(b.subarray(0, 8));
            const tBuf = Buffer.alloc(8);
            tBuf.writeBigUInt64BE(t);
            for (let k = 0; k < 8; k++) {
                aBytes[k] ^= tBuf[k];
            }
            a = aBytes;
            r[i] = Buffer.from(b.subarray(8, 16));
        }
    }

    return Buffer.concat([a, ...r]);
}

// AES Key Unwrap (RFC 3394)
function aesKeyUnwrap(kek, ciphertext) {
    if (ciphertext.length % 8 !== 0 || ciphertext.length < 16) return null;

    const n = (ciphertext.length / 8) - 1;
    let a = Buffer.from(ciphertext.subarray(0, 8));
    const r = [];
    for (let i = 0; i < n; i++) {
        r.push(Buffer.from(ciphertext.subarray((i + 1) * 8, (i + 2) * 8)));
    }

    for (let j = 5; j >= 0; j--) {
        for (let i = n - 1; i >= 0; i--) {
            const t = BigInt(n * j + i + 1);
            const tBuf = Buffer.alloc(8);
            tBuf.writeBigUInt64BE(t);
            const aXored = Buffer.from(a);
            for (let k = 0; k < 8; k++) {
                aXored[k] ^= tBuf[k];
            }
            const input = Buffer.concat([aXored, r[i]]);
            const decipher = crypto.createDecipheriv('aes-128-ecb', kek, null);
            decipher.setAutoPadding(false);
            const b = Buffer.concat([decipher.update(input), decipher.final()]);
            a = Buffer.from(b.subarray(0, 8));
            r[i] = Buffer.from(b.subarray(8, 16));
        }
    }

    // Verify IV
    const expectedIv = Buffer.from('A6A6A6A6A6A6A6A6', 'hex');
    if (!a.equals(expectedIv)) return null;

    return Buffer.concat(r);
}

module.exports = { KeyManager, aesKeyWrap, aesKeyUnwrap, SRTP_KEY_LEN, SRTP_SALT_LEN, KEK_LEN };
